server:
  # The external port exposed in docker-compose (8080)
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user_service_secured
              uri: http://user-service:8081
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
                - name: JwtAuthenticationFilter

            - id: user_service_health
              uri: http://user-service:8081
              predicates:
                - Path=/users/health

            - id: user_service_auth_post
              uri: http://user-service:8081
              predicates:
                - Path=/users/register
                - Method=POST

            - id: user_service_auth_login
              uri: http://user-service:8081
              predicates:
                - Path=/users/login
                - Method=POST

            - id: billing_service_ingestion
              uri: http://billing-service:8082
              predicates:
                - Path=/api/billing/**
              filters:
                - StripPrefix=1
                - name: JwtAuthenticationFilter
                  args: {}

            - id: billing_service_public
              uri: http://billing-service:8082
              predicates:
                - Path=/billing/health

            - id: recommendation_service_public
              uri: http://recommendation-service:8083
              predicates:
                - Path=/recommendations/health

            - id: recommendation_service_secured
              uri: http://recommendation-service:8083
              predicates:
                - Path=/api/recommendations/**
              filters:
                - StripPrefix=1
                - name: JwtAuthenticationFilter

            - id: notification_service_ws
              uri: http://notification-service:8084
              predicates:
                - Path=/ws-notifications/**

            - id: notification_service_public
              uri: http://notification-service:8084
              predicates:
                - Path=/notifications/health


jwt:
  secretKey: YmFzZTY0X2VuY29kZWRfc3VwZXJfc2VjcmV0X2tleV9mb3Jfc29hX3Byb2plY3RfMjAyNA==

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
